import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { dirname, resolve } from 'path'
import { z } from 'zod'
import { scheduleJsonPath as getScheduleJsonPath, schedulePath } from './paths.ts'

export const ScheduledJobSchema = z.object({
  name: z
    .string()
    .min(1)
    .regex(/^[a-z0-9-]+$/, 'name must be lowercase alphanumeric with dashes'),
  schedule: z.string().min(1),
  command: z.string().min(1).default('send'),
})

export type ScheduledJob = z.infer<typeof ScheduledJobSchema>

export const ScheduleSchema = z.object({
  jobs: z.array(ScheduledJobSchema),
})

export type Schedule = z.infer<typeof ScheduleSchema>

export const defaultSchedule: Schedule = {
  jobs: [
    { name: 'waify-morning', schedule: '0 0 9 * * *', command: 'send' },
    { name: 'waify-evening', schedule: '0 0 19 * * *', command: 'send' },
  ],
}

const scheduleJsonPath = getScheduleJsonPath

export const loadSchedule = (): Schedule => {
  const path = scheduleJsonPath()
  if (!existsSync(path)) return defaultSchedule
  const raw = readFileSync(path, 'utf-8')
  return ScheduleSchema.parse(JSON.parse(raw))
}

export const saveSchedule = (schedule: Schedule): void => {
  const path = scheduleJsonPath()
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, JSON.stringify(schedule, null, 2) + '\n', 'utf-8')
  regenerateOfeliaIni(schedule)
}

export type OfeliaRuntime = {
  image: string
  network: string
  hostDataDir: string
  hostEnvFile: string
}

const ofeliaRuntime = (): OfeliaRuntime => ({
  image: process.env['WAIFY_SENDER_IMAGE'] ?? 'openwa-scripts-sender:latest',
  network: process.env['WAIFY_NETWORK'] ?? 'openwa-network',
  hostDataDir: process.env['WAIFY_HOST_DATA_DIR'] ?? resolve(process.cwd(), 'data'),
  hostEnvFile: process.env['WAIFY_HOST_ENV_FILE'] ?? resolve(process.cwd(), '.env'),
})

const renderJob = (job: ScheduledJob, runtime: OfeliaRuntime): string =>
  [
    `[job-run "${job.name}"]`,
    `schedule = ${job.schedule}`,
    `image = ${runtime.image}`,
    `network = ${runtime.network}`,
    `command = ${job.command}`,
    `volume = ${runtime.hostDataDir}:/data`,
    `volume = ${runtime.hostEnvFile}:/app/.env:ro`,
  ].join('\n')

export const renderOfeliaIni = (schedule: Schedule, runtime: OfeliaRuntime = ofeliaRuntime()): string => {
  const header = [
    '# Generated by waify. Edit via TUI or `waify schedule` subcommands.',
    '# Restart the scheduler service after changes: docker compose restart scheduler',
    '',
    '[global]',
    'save-folder = /tmp/ofelia',
    '',
  ].join('\n')
  const body = schedule.jobs.map((j) => renderJob(j, runtime)).join('\n\n')
  return header + body + '\n'
}

export const regenerateOfeliaIni = (schedule: Schedule): void => {
  const path = schedulePath()
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, renderOfeliaIni(schedule), 'utf-8')
}

export const addJob = (job: ScheduledJob): Schedule => {
  const current = loadSchedule()
  if (current.jobs.some((j) => j.name === job.name)) {
    throw new Error(`Job with name "${job.name}" already exists`)
  }
  const next = { jobs: [...current.jobs, job] }
  saveSchedule(next)
  return next
}

export const removeJob = (name: string): Schedule => {
  const current = loadSchedule()
  const next = { jobs: current.jobs.filter((j) => j.name !== name) }
  saveSchedule(next)
  return next
}
