import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { dirname } from 'path'
import { z } from 'zod'
import { dataDir, scheduleJsonPath as getScheduleJsonPath, schedulePath } from './paths.ts'

const CRON_RANGES: ReadonlyArray<readonly [number, number]> = [
  [0, 59], // seconds
  [0, 59], // minutes
  [0, 23], // hours
  [1, 31], // day-of-month
  [1, 12], // month
  [0, 7],  // day-of-week
]

const STEP_RE = /^(\*|\d+)\/\d+$/
const RANGE_RE = /^\d+-\d+$/

const isValidCronField = (field: string, [min, max]: readonly [number, number]): boolean => {
  if (field === '*') return true
  if (STEP_RE.test(field) || RANGE_RE.test(field)) return true
  const n = Number(field)
  return Number.isInteger(n) && n >= min && n <= max
}

export const isValidCron = (value: string): boolean => {
  const fields = value.trim().split(/\s+/)
  return fields.length === 6 && fields.every((f, i) => isValidCronField(f, CRON_RANGES[i]!))
}

export const ScheduledJobSchema = z.object({
  name: z
    .string()
    .min(1)
    .regex(/^[a-z0-9-]+$/, 'name must be lowercase alphanumeric with dashes'),
  schedule: z
    .string()
    .min(1)
    .refine(isValidCron, { message: 'schedule must be a 6-field cron expression (e.g. 0 0 9 * * *)' }),
  command: z.string().min(1).default('send'),
})

export type ScheduledJob = z.infer<typeof ScheduledJobSchema>

export const ScheduleSchema = z.object({
  jobs: z.array(ScheduledJobSchema),
})

export type Schedule = z.infer<typeof ScheduleSchema>

export const defaultSchedule: Schedule = {
  jobs: [
    { name: 'waify-morning', schedule: '0 0 9 * * *', command: 'send' },
    { name: 'waify-evening', schedule: '0 0 19 * * *', command: 'send' },
  ],
}

const scheduleJsonPath = getScheduleJsonPath

export const loadSchedule = (): Schedule => {
  const path = scheduleJsonPath()
  if (!existsSync(path)) return defaultSchedule
  const raw = readFileSync(path, 'utf-8')
  return ScheduleSchema.parse(JSON.parse(raw))
}

export const saveSchedule = (schedule: Schedule): void => {
  const path = scheduleJsonPath()
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, JSON.stringify(schedule, null, 2) + '\n', 'utf-8')
  regenerateOfeliaIni(schedule)
}

export type OfeliaRuntime = {
  image: string
  network: string
  hostDataDir: string
  apiBaseUrl: string
}

const ofeliaRuntime = (): OfeliaRuntime => ({
  image: process.env['WAIFY_SENDER_IMAGE'] ?? 'openwa-scripts-sender:latest',
  network: process.env['WAIFY_NETWORK'] ?? 'waify-network',
  hostDataDir: process.env['WAIFY_HOST_DATA_DIR'] ?? dataDir(),
  apiBaseUrl: process.env['WAIFY_API_INTERNAL_URL'] ?? 'http://openwa-api:2785',
})

// Ofelia parses `environment = KEY=VALUE`, so the `=` inside the value must be
// escaped as `\=` to avoid being read as the INI key/value separator.
const renderEnv = (key: string, value: string): string => `environment = ${key}\\=${value}`

const renderJob = (job: ScheduledJob, runtime: OfeliaRuntime): string =>
  [
    `[job-run "${job.name}"]`,
    `schedule = ${job.schedule}`,
    `image = ${runtime.image}`,
    `network = ${runtime.network}`,
    // The sender image is built locally, so Ofelia must not try to pull it
    // (default Pull=true → 404 pull access denied). See mcuadros/ofelia#55.
    `pull = false`,
    `command = ${job.command}`,
    // WAIFY_DATA_DIR points config/.env resolution at the mounted /data dir;
    // OPENWA_BASE_URL reaches the API by service name over waify-network
    // (the mounted config.json says localhost, which is wrong inside a container).
    renderEnv('WAIFY_DATA_DIR', '/data'),
    renderEnv('OPENWA_BASE_URL', runtime.apiBaseUrl),
    `volume = ${runtime.hostDataDir}:/data`,
  ].join('\n')

export const renderOfeliaIni = (schedule: Schedule, runtime: OfeliaRuntime = ofeliaRuntime()): string => {
  const header = [
    '# Generated by waify. Edit via TUI or `waify schedule` subcommands.',
    '# Restart the scheduler service after changes: docker compose restart scheduler',
    '',
    '[global]',
    'save-folder = /tmp/ofelia',
    '',
  ].join('\n')
  const body = schedule.jobs.map((j) => renderJob(j, runtime)).join('\n\n')
  return header + body + '\n'
}

export const regenerateOfeliaIni = (schedule: Schedule): void => {
  const path = schedulePath()
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, renderOfeliaIni(schedule), 'utf-8')
}

export const addJob = (job: ScheduledJob): Schedule => {
  const current = loadSchedule()
  if (current.jobs.some((j) => j.name === job.name)) {
    throw new Error(`Job with name "${job.name}" already exists`)
  }
  const next = { jobs: [...current.jobs, job] }
  saveSchedule(next)
  return next
}

export const removeJob = (name: string): Schedule => {
  const current = loadSchedule()
  const next = { jobs: current.jobs.filter((j) => j.name !== name) }
  saveSchedule(next)
  return next
}
